Repository crispindeity/issue-tracker, pull requests merged in 2022-10, with the labels that each got.

#199 [geombong/issue-tracker#198] edit: optimizationIssueQuery
  BE/src/main/java/team20/issuetracker/domain/issue/IssueRepository.java
  BE/src/main/java/team20/issuetracker/service/IssueService.java
  BE/src/main/java/team20/issuetracker/service/dto/response/ResponseReadAllIssueDto.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: 📬 API, BE

#205 Feat/find all issue page
  BE/src/main/java/team20/issuetracker/controller/IssueController.java
  BE/src/main/java/team20/issuetracker/controller/page/CustomPage.java
  BE/src/main/java/team20/issuetracker/controller/page/CustomPageable.java
  BE/src/main/java/team20/issuetracker/domain/issue/IssueRepository.java
  BE/src/main/java/team20/issuetracker/domain/issue/IssueStatus.java
  BE/src/main/java/team20/issuetracker/service/IssueService.java
  BE/src/main/java/team20/issuetracker/service/dto/response/ResponseReadAllIssueDto.java
Labels: 📬 API, BE

#207 [geombong/issue-tracker#206] fix: get issue by stuats
  BE/src/main/java/team20/issuetracker/controller/IssueController.java
Labels: 🐞 BugFix, 📬 API, BE

#208 Refactor/milestone api
  FE/src/apis/milestoneApi.ts
  FE/src/components/MilestoneList/MilestoneItem/MilestoneForm/index.tsx
  FE/src/components/MilestoneList/MilestoneItem/index.tsx
  FE/src/types/milestoneTypes.ts
Labels: FE

#210 [geombong/issue-tracker#209] feat: Custom Enum To String Converter
  BE/src/main/java/team20/issuetracker/config/StringToIssueStats.java
  BE/src/main/java/team20/issuetracker/config/StringToMilestoneStatus.java
  BE/src/main/java/team20/issuetracker/config/WebConfig.java
  BE/src/main/java/team20/issuetracker/controller/IssueController.java
  BE/src/main/java/team20/issuetracker/domain/issue/IssueStatus.java
  BE/src/main/java/team20/issuetracker/domain/milestone/MilestoneStatus.java
  BE/src/main/resources/data.sql
Labels: 📬 API, BE

#216 :heavy_plus_sign: [geombong/issue-tracker#215] Add Querydsl Setting
  BE/.gitignore
  BE/build.gradle
Labels: ⚙ Setting, 📬 API

#221 Add Querydsl
  BE/build.gradle
  BE/src/main/java/team20/issuetracker/controller/IssueController.java
  BE/src/main/java/team20/issuetracker/controller/page/CustomPage.java
  BE/src/main/java/team20/issuetracker/controller/page/CustomPageable.java
  BE/src/main/java/team20/issuetracker/domain/issue/IssueRepository.java
  BE/src/main/java/team20/issuetracker/domain/issue/IssueRepositoryCustom.java
  BE/src/main/java/team20/issuetracker/domain/issue/IssueRepositoryImpl.java
  BE/src/main/java/team20/issuetracker/service/IssueService.java
Labels: ✨ Feature, BE

#223 [geombong/issue-tracker#222] Fix: Add Issue Lookup Count Query
  BE/src/main/java/team20/issuetracker/domain/issue/IssueRepositoryImpl.java
Labels: 🐞 BugFix, 📬 API, BE

#224 [geombong/issue-tracker#220] Edit: Modify IssueRepositoryImpl
  BE/src/main/java/team20/issuetracker/domain/issue/IssueRepositoryImpl.java
Labels: 📬 API, BE

#227 [geombong/issue-tracker#226] Fix: addMultiLabelSearch
  BE/src/main/java/team20/issuetracker/domain/issue/IssueRepositoryCustom.java
  BE/src/main/java/team20/issuetracker/domain/issue/IssueRepositoryImpl.java
  BE/src/main/java/team20/issuetracker/service/IssueService.java
Labels: 🐞 BugFix, 📬 API, BE
