Repository crispindeity/issue-tracker, pull requests merged in 2022-07, with the labels that each got.

#72 [geombong/issue-trakcer#70] Feat: Create Domain
  BE/src/main/java/team20/issuetracker/domain/assignee/Assignee.java
  BE/src/main/java/team20/issuetracker/domain/comment/Comment.java
  BE/src/main/java/team20/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team20/issuetracker/domain/issue/IssueStatus.java
  BE/src/main/java/team20/issuetracker/domain/label/Label.java
  BE/src/main/java/team20/issuetracker/domain/member/Member.java
  BE/src/main/java/team20/issuetracker/domain/member/MemberRepository.java
  BE/src/main/java/team20/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/team20/issuetracker/login/oauth/dto/UserProfile.java
  BE/src/main/java/team20/issuetracker/login/oauth/service/OauthService.java
Labels: ✨ Feature, BE

#73 Feat/entity mapping
  BE/src/main/java/team20/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team20/issuetracker/domain/milestone/Milestone.java
Labels: ✨ Feature, BE

#75 [geombong/issue-tracker#74] Chore: Check API And Domain
  BE/src/main/java/team20/issuetracker/domain/comment/Comment.java
  BE/src/main/java/team20/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team20/issuetracker/domain/label/Label.java
  BE/src/main/java/team20/issuetracker/domain/milestone/Milestone.java
Labels: 📬 API, BE

#78 Feat/add redis
  BE/build.gradle
  BE/src/main/java/team20/issuetracker/config/RedisRepositoryConfig.java
  BE/src/main/java/team20/issuetracker/login/jwt/JwtTokenProvider.java
  BE/src/main/java/team20/issuetracker/login/oauth/service/OauthService.java
Labels: ✨ Feature, BE

#81 [geombong/issue-tracker#80] Test: Create Issue Test API
  BE/src/main/java/team20/issuetracker/domain/assignee/Assignee.java
  BE/src/main/java/team20/issuetracker/domain/comment/Comment.java
  BE/src/main/java/team20/issuetracker/domain/label/Label.java
  BE/src/main/java/team20/issuetracker/domain/milestone/Milestone.java
  BE/src/test/java/team20/issuetracker/config/TestWebConfig.java
  BE/src/test/java/team20/issuetracker/domain/issue/IssueRepositoryTest.java
Labels: 📬 API, BE, ✅ Test

#83 [geombong/issue-tracker#82] Feat: refresh token validation
  BE/src/main/java/team20/issuetracker/config/WebConfig.java
  BE/src/main/java/team20/issuetracker/controller/OauthController.java
  BE/src/main/java/team20/issuetracker/login/oauth/dto/RequestRefreshDto.java
  BE/src/main/java/team20/issuetracker/service/OauthService.java
Labels: ✨ Feature, BE

#87 [geombong/issue-tracker#84] Chore: Delete DTO Builder
  BE/src/main/java/team20/issuetracker/domain/assignee/ReadAssigneeDto.java
  BE/src/main/java/team20/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team20/issuetracker/domain/issue/SaveIssueDto.java
  BE/src/main/java/team20/issuetracker/domain/label/ReadLabelDto.java
  BE/src/main/java/team20/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/team20/issuetracker/domain/milestone/ReadMilestoneDto.java
Labels: ✨ Feature, BE

#89 Feat/edit entitiy mapping
  BE/src/main/java/team20/issuetracker/domain/assignee/Assignee.java
  BE/src/main/java/team20/issuetracker/domain/comment/Comment.java
  BE/src/main/java/team20/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team20/issuetracker/domain/issue/SaveIssueDto.java
  BE/src/main/java/team20/issuetracker/domain/label/Label.java
Labels: 🔨 Refactor, 📬 API

#93 Feat/issue create test
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/team20/issuetracker/domain/comment/Comment.java
  BE/src/main/java/team20/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team20/issuetracker/domain/issue/IssueComment.java
  BE/src/main/java/team20/issuetracker/domain/issue/SaveIssueDto.java
  BE/src/main/java/team20/issuetracker/domain/label/Label.java
  BE/src/main/java/team20/issuetracker/service/IssueService.java
  BE/src/test/java/team20/issuetracker/IssuetrackerApplicationTests.java
  BE/src/test/java/team20/issuetracker/config/TestWebConfig.java
  BE/src/test/java/team20/issuetracker/domain/issue/IssueCreateTest.java
  BE/src/test/java/team20/issuetracker/domain/issue/IssueRepositoryTest.java
Labels: 📬 API, BE, ✅ Test

#96 Feat/create milestone api
  BE/src/main/java/team20/issuetracker/controller/MilestoneController.java
  BE/src/main/java/team20/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/team20/issuetracker/domain/milestone/requestDto/SaveMilestoneDto.java
  BE/src/main/java/team20/issuetracker/service/MilestoneService.java
  BE/src/test/java/team20/issuetracker/domain/milestone/MilestoneCreateTest.java
Labels: ✨ Feature, 📬 API, BE

#97 Feat/create label api#94
  BE/.gitignore
  BE/src/main/java/team20/issuetracker/controller/LabelController.java
  BE/src/main/java/team20/issuetracker/controller/LabelService.java
  BE/src/main/java/team20/issuetracker/domain/label/Label.java
  BE/src/main/java/team20/issuetracker/domain/label/ResponseLabelDto.java
  BE/src/main/java/team20/issuetracker/domain/label/ResponseLabelsDto.java
  BE/src/main/java/team20/issuetracker/domain/label/SaveLabelDto.java
  BE/src/main/java/team20/issuetracker/domain/label/UpdateLabelDto.java
Labels: ✨ Feature, 📬 API, BE

#101 Feat/milestone rud api
  BE/src/main/java/team20/issuetracker/controller/MilestoneController.java
  BE/src/main/java/team20/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/team20/issuetracker/domain/milestone/MilestoneStatus.java
  BE/src/main/java/team20/issuetracker/domain/milestone/request/SaveMilestoneDto.java
  BE/src/main/java/team20/issuetracker/domain/milestone/request/UpdateMilestoneDto.java
  BE/src/main/java/team20/issuetracker/domain/milestone/response/MilestoneDto.java
  BE/src/main/java/team20/issuetracker/domain/milestone/response/ReadAllMilestones.java
  BE/src/main/java/team20/issuetracker/service/MilestoneService.java
  BE/src/test/java/team20/issuetracker/domain/milestone/MilestoneCreateTest.java
  BE/src/test/java/team20/issuetracker/domain/milestone/MilestoneDeleteTest.java
  BE/src/test/java/team20/issuetracker/domain/milestone/MilestoneReadTest.java
  BE/src/test/java/team20/issuetracker/domain/milestone/MilestoneUpdateTest.java
Labels: ✨ Feature, 📬 API, BE, ✅ Test

#102 Feat/add label validation
  BE/build.gradle
  BE/src/main/java/team20/issuetracker/controller/LabelController.java
  BE/src/main/java/team20/issuetracker/domain/label/Label.java
  BE/src/main/java/team20/issuetracker/domain/label/RequestLabelDto.java
  BE/src/main/java/team20/issuetracker/domain/label/ResponseLabelDto.java
  BE/src/main/java/team20/issuetracker/domain/label/ResponseLabelsDto.java
  BE/src/main/java/team20/issuetracker/domain/label/SaveLabelDto.java
  BE/src/main/java/team20/issuetracker/domain/label/UpdateLabelDto.java
  BE/src/main/java/team20/issuetracker/exceptionhandler/GlobalExceptionHandler.java
  BE/src/main/java/team20/issuetracker/service/LabelService.java
Labels: ✨ Feature, 📬 API, BE

#105 Change Dto Package
  BE/src/main/java/team20/issuetracker/controller/IssueController.java
  BE/src/main/java/team20/issuetracker/controller/LabelController.java
  BE/src/main/java/team20/issuetracker/controller/MilestoneController.java
  BE/src/main/java/team20/issuetracker/controller/OauthController.java
  BE/src/main/java/team20/issuetracker/domain/label/Label.java
  BE/src/main/java/team20/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/team20/issuetracker/domain/milestone/response/ReadAllMilestones.java
  BE/src/main/java/team20/issuetracker/login/oauth/OauthProvider.java
  BE/src/main/java/team20/issuetracker/login/oauth/config/OauthConfig.java
  BE/src/main/java/team20/issuetracker/login/oauth/config/OauthProperties.java
  BE/src/main/java/team20/issuetracker/login/oauth/dto/request/RequestRefreshDto.java
  BE/src/main/java/team20/issuetracker/login/oauth/dto/request/RequestUserDto.java
  BE/src/main/java/team20/issuetracker/login/oauth/dto/response/ResponseLoginDto.java
  BE/src/main/java/team20/issuetracker/login/oauth/dto/response/ResponseOauthTokenDto.java
  BE/src/main/java/team20/issuetracker/service/IssueService.java
  BE/src/main/java/team20/issuetracker/service/LabelService.java
  BE/src/main/java/team20/issuetracker/service/MilestoneService.java
  BE/src/main/java/team20/issuetracker/service/OauthService.java
  BE/src/main/java/team20/issuetracker/service/dto/request/RequestLabelDto.java
  BE/src/main/java/team20/issuetracker/service/dto/request/RequestSaveIssueDto.java
  BE/src/main/java/team20/issuetracker/service/dto/request/RequestSaveMilestoneDto.java
  BE/src/main/java/team20/issuetracker/service/dto/request/RequestUpdateMilestoneDto.java
  BE/src/main/java/team20/issuetracker/service/dto/response/ResponseLabelDto.java
  BE/src/main/java/team20/issuetracker/service/dto/response/ResponseLabelsDto.java
  BE/src/main/java/team20/issuetracker/service/dto/response/ResponseMilestoneDto.java
  BE/src/main/java/team20/issuetracker/service/dto/response/ResponseReadAllMilestonesDto.java
  BE/src/test/java/team20/issuetracker/domain/issue/IssueCreateTest.java
  BE/src/test/java/team20/issuetracker/domain/milestone/MilestoneCreateTest.java
  BE/src/test/java/team20/issuetracker/domain/milestone/MilestoneDeleteTest.java
  BE/src/test/java/team20/issuetracker/domain/milestone/MilestoneReadTest.java
  BE/src/test/java/team20/issuetracker/domain/milestone/MilestoneUpdateTest.java
Labels: 🔨 Refactor, BE

#107 Create Assignee Read API
  BE/src/main/java/team20/issuetracker/controller/AssigneeController.java
  BE/src/main/java/team20/issuetracker/domain/assginee/Assignee.java
  BE/src/main/java/team20/issuetracker/service/AssigneeService.java
  BE/src/main/java/team20/issuetracker/service/dto/response/ResponseAssigneeDto.java
  BE/src/main/java/team20/issuetracker/service/dto/response/ResponseAssigneesDto.java
Labels: ✨ Feature, 📬 API, BE

#111 Add Label CRUD Test
  BE/src/main/java/team20/issuetracker/service/LabelService.java
  BE/src/main/java/team20/issuetracker/service/dto/request/RequestLabelDto.java
  BE/src/test/java/team20/issuetracker/service/LabelServiceTest.java
Labels: 📬 API, BE, ✅ Test

#114 Add JPA Auditing(Milestone)
  .github/workflows/gradle.yml
  BE/src/main/java/team20/issuetracker/IssuetrackerApplication.java
  BE/src/main/java/team20/issuetracker/config/AuditingConfig.java
  BE/src/main/java/team20/issuetracker/controller/MilestoneController.java
  BE/src/main/java/team20/issuetracker/controller/OauthController.java
  BE/src/main/java/team20/issuetracker/domain/AuditingFields.java
  BE/src/main/java/team20/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team20/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/team20/issuetracker/domain/milestone/MilestoneRepository.java
  BE/src/main/java/team20/issuetracker/login/jwt/JwtTokenProvider.java
  BE/src/main/java/team20/issuetracker/login/oauth/dto/request/RequestRefreshDto.java
  BE/src/main/java/team20/issuetracker/login/oauth/dto/request/RequestUserDto.java
  BE/src/main/java/team20/issuetracker/service/IssueService.java
  BE/src/main/java/team20/issuetracker/service/MilestoneService.java
  BE/src/main/java/team20/issuetracker/service/OauthService.java
  BE/src/main/java/team20/issuetracker/service/dto/request/RequestSaveIssueDto.java
  BE/src/main/java/team20/issuetracker/service/dto/request/RequestSaveMilestoneDto.java
  BE/src/main/java/team20/issuetracker/service/dto/request/RequestUpdateMilestoneDto.java
  BE/src/main/java/team20/issuetracker/service/dto/response/ResponseMilestoneDto.java
  BE/src/main/java/team20/issuetracker/util/JwtUtils.java
  BE/src/main/resources/application-oauth2.yml
  BE/src/test/java/team20/issuetracker/domain/issue/IssueCreateTest.java
  BE/src/test/java/team20/issuetracker/domain/milestone/MilestoneCreateTest.java
  BE/src/test/java/team20/issuetracker/domain/milestone/MilestoneDeleteTest.java
  BE/src/test/java/team20/issuetracker/domain/milestone/MilestoneReadTest.java
  BE/src/test/java/team20/issuetracker/domain/milestone/MilestoneUpdateTest.java
  BE/src/test/java/team20/issuetracker/service/LabelServiceTest.java
Labels: ✨ Feature, 📬 API, BE

#115 [geombong/issue-tracker] Fix: test bug fix
  BE/src/test/java/team20/issuetracker/service/LabelServiceTest.java
Labels: 🐞 BugFix, BE

#113 [FE] Label form features
  .github/workflows/react.yml
  FE/src/components/FilterBar/index.tsx
  FE/src/components/IssueList/IssueListHeader/data.ts
  FE/src/components/IssueList/IssueListHeader/index.tsx
  FE/src/components/LabelForm/ColorChangeButton/index.tsx
  FE/src/components/LabelForm/index.tsx
  FE/src/components/LabelForm/type.ts
  FE/src/components/common/DropDown/DetailsMenu/index.tsx
  FE/src/components/common/DropDown/style.ts
  FE/src/components/common/DropDown/type.ts
  FE/src/components/common/Input/index.tsx
  FE/src/components/common/Input/type.ts
  FE/src/constants/api.ts
  FE/src/hooks/useInput.tsx
  FE/src/icons/Label.ts
  FE/src/mocks/Assignees/data.ts
  FE/src/mocks/Assignees/index.ts
  FE/src/mocks/Issues/data.ts
  FE/src/mocks/Issues/index.ts
  FE/src/mocks/handlers.ts
  FE/src/utils/dropdown.ts
  FE/src/utils/label.ts
Labels: ✨ Feature, FE

#116 Add JPA Auditing
  BE/src/main/java/team20/issuetracker/controller/LabelController.java
  BE/src/main/java/team20/issuetracker/domain/label/Label.java
  BE/src/main/java/team20/issuetracker/domain/label/LabelRepository.java
  BE/src/main/java/team20/issuetracker/login/interceptor/LoginInterceptor.java
  BE/src/main/java/team20/issuetracker/login/jwt/JwtTokenProvider.java
  BE/src/main/java/team20/issuetracker/service/LabelService.java
  BE/src/main/java/team20/issuetracker/service/dto/request/RequestLabelDto.java
  BE/src/main/java/team20/issuetracker/service/dto/request/RequestUpdateMilestoneDto.java
  BE/src/test/java/team20/issuetracker/service/LabelServiceTest.java
Labels: ✨ Feature, 📬 API, BE

#119 Feat/create issue read api
  BE/src/main/java/team20/issuetracker/controller/IssueController.java
  BE/src/main/java/team20/issuetracker/domain/assginee/Assignee.java
  BE/src/main/java/team20/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team20/issuetracker/domain/issue/IssueAssigneeRepository.java
  BE/src/main/java/team20/issuetracker/domain/issue/IssueLabelRepository.java
  BE/src/main/java/team20/issuetracker/domain/issue/IssueRepository.java
  BE/src/main/java/team20/issuetracker/domain/label/Label.java
  BE/src/main/java/team20/issuetracker/service/IssueService.java
  BE/src/main/java/team20/issuetracker/service/dto/response/ResponseIssueDto.java
Labels: ✨ Feature, 📬 API, BE

#125 Create Comment API
  BE/src/main/java/team20/issuetracker/controller/CommentController.java
  BE/src/main/java/team20/issuetracker/domain/comment/Comment.java
  BE/src/main/java/team20/issuetracker/service/CommentService.java
  BE/src/main/java/team20/issuetracker/service/dto/request/RequestCommentDto.java
Labels: ✨ Feature, 📬 API, BE
